-- BUS_PROJECT
INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目1','地址1',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目2','地址2',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目3','地址3',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目4','地址4',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目5','地址5',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目6','地址6',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目7','地址7',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目8','地址8',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目9','地址9',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目10','地址10',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目11','地址11',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目12','地址12',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目13','地址13',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目14','地址14',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目15','地址15',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目16','地址16',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目17','地址17',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目18','地址18',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目19','地址19',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目20','地址20',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目21','地址21',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目22','地址22',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目23','地址23',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目24','地址24',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);

INSERT INTO `shecc`.`bus_project` (`NAME`,`ADDRESS`,`LONGITUDE`,`LATITUDE`,`PICTURE`,`INPUT_UID`,`INPUT_UNAME`,`INPUT_TIME`,`CHECK_UID`,`CHECK_UNAME`,`CHECK_TIME`,`LAST_MODIFY_UID`,`LAST_MODIFY_UNAME`,`LAST_MODIFY_TIME`,`ARCHIVE_FLAG`)
VALUES ('项目25','地址25',10,20,'/data/eoms/pic/project/20161103001',1,‘ADMIN’,now(),1,‘ADMIN’,now(),1,‘ADMIN’,now(),1);